# Generated by Django 5.0.7 on 2024-07-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=100)),
                ('dtEntrada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
